set (PETSC_HAVE_MKL_SPARSE YES)
set (PETSC_HAVE_MKL_SPARSE_OPTIMIZE YES)
set (PETSC_HAVE_BLASLAPACK YES)
set (PETSC_HAVE_MKL YES)
set (PETSC_HAVE_MPI YES)
set (PETSC_HAVE_MPI_F90MODULE YES)
set (PETSC_HAVE_MPI_IALLREDUCE YES)
set (PETSC_HAVE_I_MPI_NUMVERSION 0)
set (PETSC_HAVE_MPI_REDUCE_SCATTER_BLOCK YES)
set (PETSC_HAVE_MPI_IN_PLACE YES)
set (PETSC_HAVE_MPI_COMM_C2F YES)
set (PETSC_HAVE_MPI_GET_LIBRARY_VERSION YES)
set (PETSC_HAVE_MPI_COMBINER_CONTIGUOUS YES)
set (PETSC_HAVE_MPI_INT64_T YES)
set (PETSC_HAVE_MPI_TYPE_GET_EXTENT YES)
set (PETSC_HAVE_MPI_WIN_CREATE YES)
set (PETSC_HAVE_MPI_TYPE_DUP YES)
set (PETSC_HAVE_MPI_INIT_THREAD YES)
set (PETSC_HAVE_MPI_COMBINER_NAMED YES)
set (PETSC_HAVE_MPI_LONG_DOUBLE YES)
set (PETSC_HAVE_MPI_COMM_F2C YES)
set (PETSC_HAVE_MPI_TYPE_GET_ENVELOPE YES)
set (PETSC_HAVE_MPI_REDUCE_SCATTER YES)
set (PETSC_HAVE_MPI_COMBINER_DUP YES)
set (PETSC_HAVE_MPIIO YES)
set (PETSC_HAVE_MPI_COMM_SPAWN YES)
set (PETSC_HAVE_MPI_FINT YES)
set (PETSC_HAVE_MPI_IBARRIER YES)
set (PETSC_HAVE_MPI_ALLTOALLW YES)
set (PETSC_HAVE_MPI_REDUCE_LOCAL YES)
set (PETSC_HAVE_MPI_REPLACE YES)
set (PETSC_HAVE_MPI_EXSCAN YES)
set (PETSC_HAVE_MPI_C_DOUBLE_COMPLEX YES)
set (PETSC_HAVE_MPI_FINALIZED YES)
set (PETSC_HAVE_ACCESS YES)
set (PETSC_HAVE_SIGNAL YES)
set (PETSC_HAVE__MKDIR YES)
set (PETSC_HAVE__LSEEK YES)
set (PETSC_HAVE__GETCWD YES)
set (PETSC_HAVE_MEMMOVE YES)
set (PETSC_HAVE_RAND YES)
set (PETSC_HAVE__SLEEP YES)
set (PETSC_HAVE_TIME YES)
set (PETSC_HAVE_GETCWD YES)
set (PETSC_HAVE_LSEEK YES)
set (PETSC_HAVE__VSNPRINTF YES)
set (PETSC_HAVE__ACCESS YES)
set (PETSC_HAVE_STRICMP YES)
set (PETSC_SIGNAL_CAST  )
set (PETSC_HAVE_VA_COPY YES)
set (PETSC_HAVE_CLOCK YES)
set (PETSC_USE_WINDOWS_GRAPHICS YES)
set (PETSC_USE_ISATTY YES)
set (PETSC_USE_SINGLE_LIBRARY 1)
set (PETSC_USE_MICROSOFT_TIME YES)
set (PETSC_USE_INFO YES)
set (PETSC_USE_BACKWARD_LOOP 1)
set (PETSC_USE_MALLOC_COALESCED YES)
set (PETSC_USE_LOG YES)
set (PETSC_USE_CTABLE 1)
set (PETSC_USE_COMPLEX NO)
set (PETSC_USE_REAL_DOUBLE YES)
set (PETSC_CLANGUAGE_C YES)
set (PETSC_HAVE_FORTRAN YES)
set (PETSC_USING_F90 YES)
set (PETSC_USING_F2003 YES)
set (PETSC_HAVE_CXX YES)
set (BUILD_SHARED_LIBS YES)
find_library (PETSC_MKL_INTEL_LP64_DLL_LIB mkl_intel_lp64_dll HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_MKL_INTEL_THREAD_DLL_LIB mkl_intel_thread_dll HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_MKL_CORE_DLL_LIB mkl_core_dll HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_IOMP5MD_LIB iomp5md HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_IMPI_LIB impi HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_GDI32_LIB Gdi32 HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_USER32_LIB User32 HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_ADVAPI32_LIB Advapi32 HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_KERNEL32_LIB Kernel32 HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
find_library (PETSC_WS2_32_LIB Ws2_32 HINTS "/cygdrive/E/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64" "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/lib/release" )
mark_as_advanced (PETSC_MKL_INTEL_LP64_DLL_LIB PETSC_MKL_INTEL_THREAD_DLL_LIB PETSC_MKL_CORE_DLL_LIB PETSC_IOMP5MD_LIB PETSC_IMPI_LIB PETSC_GDI32_LIB PETSC_USER32_LIB PETSC_ADVAPI32_LIB PETSC_KERNEL32_LIB PETSC_WS2_32_LIB)
set (PETSC_PACKAGE_LIBS "${PETSC_MKL_INTEL_LP64_DLL_LIB}" "${PETSC_MKL_INTEL_THREAD_DLL_LIB}" "${PETSC_MKL_CORE_DLL_LIB}" "${PETSC_IOMP5MD_LIB}" "${PETSC_IMPI_LIB}" "${PETSC_GDI32_LIB}" "${PETSC_USER32_LIB}" "${PETSC_ADVAPI32_LIB}" "${PETSC_KERNEL32_LIB}" "${PETSC_WS2_32_LIB}")
set (PETSC_PACKAGE_INCLUDES "/cygdrive/E/Program Files (x86)/IntelSWTools/mpi/2018.1.156/intel64/include")
